version: '3.3'
services:
  opencv_app:
    container_name: opencv-container
    build:
      context: .
      dockerfile: Dockerfile
    command: 'python app.py'
    restart: unless-stopped
    volumes:
      - .:/app
    # environment:
    #   - NAME=World
    ports:
      - "8080:8080"





