version: '3.3'
services:
  opencv_app:
    container_name: opencv-container
    build:
      context: .
      dockerfile: Dockerfile
    # command: 'python app.py'
    restart: unless-stopped
    volumes:
      - .:/app
    ports:
      - "85:8080"
